.github/workflows/reviewdog.yml, go.mod, go.sum
=> Run go mod tidy and add workflow

go.mod, go.sum, main.go
=> Add small validation

.github/release.yml
リリースノートの構成を設定するファイルを作成
この PR マージ後、リリース時に意図した構成でリリースノートが作成されるか確認する
=> CVS-156 リリースノートの設定ファイルの作成

.github/workflows/coverage.yaml, .gitignore, Makefile
テストカバレッジをGitHub Pagesで確認できるようにする
CIが正常に動いてPagesが見れるのを確認する
=> CVS-170 Deploy test coverage in github pages

.github/workflows/coverage.yaml
=> CVS-170 fix script error

.github/workflows/coverage.yaml, .github/workflows/test.yml, .gitignore, Makefile
壊れそうなWorkflowがあったので修正
CIが動くか確認する
=> CVS-171 動作しない可能性があるWorkflowを修正

README.md, middleware/log.go
=> CVS-170 Add coverage badge in README.md

.air.toml, Makefile, README.md
開発中にホットリロードをできるようにした
`make dev` が動く事を確認する
=> CVS-172 ホットリロードをできるようにする

.env.sample, cmd/server/main.go, handler/handler.go, test/resources/socks/0bfb8def-86ed-4b9d-8826-66a6ab1c1491.sock
電源操作・状態取得に必要なデータ, コードを作成した
print デバッグを行った
`cmd/server/main.go: 43`
```go
socketsDirEnv := os.Getenv("SOCKETS_DIR")
_, err = os.ReadDir(socketsDirEnv)
if err != nil && errors.Is(err, fs.ErrNotExist) {
log.Fatal(err.Error())
}
fmt.Println(socketsDirEnv)
```
`.env` ファイルから環境変数が取得できている
```
>>> $ ./bin/server 
/home/chaya2z/GolandProjects/CharV/CharV-backend/test/resources/socks
```
=> CVS-174 電源関連の前提の作成

renovate.json
renovateのブランチでgo mod tidyする設定を忘れた
CI通るのを確認する
=> CVS-188 renovateの設定を修正

cmd/server/main.go, go.mod, go.sum, pkg/qemu/vm.go
=> CVS-186 backendでstart用のエンドポイントを作成

pkg/qemu/vm.go, pkg/qemu/vm_test.go
=> CVS-149 エラー出力を強化

Makefile, cmd/server/develop.go, cmd/server/main.go, cmd/server/production.go, go.mod, go.sum, middleware/log.go
=> CVS-190 ripzapの代わりにzapを使う

.github/workflows/cd.yaml
動作確認
development 環境に自動デプロイするワークフローを作成した
merge して動作確認
=> CVS-191 development環境のデプロイワークフロー

.github/workflows/cd.yaml
secrets の変数名を間違えて読み込めていなかったので修正した
merge して動作テスト
=> CVS-197 WIP: secrets の変数名を修正

handler/handler.go, pkg/qemu/type.go, pkg/qemu/vm.go
rebootのエンドポイントを追加
(KVMの操作がともうなうため既存の仕組みでテストが書けない。一旦スルーして良いものか相談したい)
curlでの確認
=> CVS-196 rebootのエンドポイントを追加

Makefile
=> CVS-204 makefileの修正

.github/workflows/cd.yaml
self-hosted runner から gitub の runner に移行
merge して動作テスト
=> CVS-210 runner の実行環境を変更

.github/workflows/deploy-prd.yaml, .github/workflows/deploy-stg.yaml
production 環境へデプロイする GitHub Actions のワークフローを作成した
Action を実行してデプロイされるか確認。
Production 環境にブラウザからアクセスし、正しくウェブページが表示されていることを確認した。
=> CVS-211 production環境への自動デプロイを作成

.github/workflows/deploy-prd.yaml
=> CVS-215 prd 環境へのデプロイイベントのトリガーを修正

.github/release.yml
=> CVS-214 リリースノートに載せる authors から renovate を除外

handler/handler.go, pkg/qemu/vm.go
=> CVS-220 vm削除の処理を実装

.github/workflows/reviewdog.yml, .golangci.yaml, Makefile, cmd/server/main.go, go.mod, infrastructure/disk/qcow2.go, infrastructure/file/vm.go, infrastructure/sockets/qmp.go, infrastructure/sockets/vnc.go, interfaces/controller/controller.go, interfaces/controller/vnc.go, interfaces/errors/errors.go, interfaces/router/router.go, usecase/models/vm.go, usecase/vm/qemu/qemu.go
- VMがない時に404を返せるようにエラーハンドリングの見直し
- VM編集用のエンドポイントを作成
APIから期待通りに取得できるか確認する
=> CVS-242 VM詳細エンドポイントを使えるようにする

.github/workflows/reviewdog.yml, usecase/host/host_test.go, usecase/models/mocks/VmDataAccess.go, usecase/models/mocks/VmUseCase.go, usecase/vm/qemu/qemu_test.go
テストコードを追加した
テストコードを実行する
テスト自体の正しさはレビューで確認する
=> CVS-249 VMの作成・取得・更新・削除のテストコードを追加

README.md
=> CVS-264 README を作成
